version: '4'

services:
  typer-db:
    image: postgres:17-alpine
    container_name: typer-postgres-database
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      - 'POSTGRES_USER=${DB_USERNAME:-postgres}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD:-}'
      - 'POSTGRES_DB=${DB_DATABASE:-typer}'
    env_file:
      - .env
    volumes:
      - typer-data:/var/lib/postgresql/data

volumes:
  typer-data:
    driver: local